web:
  image: nginx:latest
  ports:
    - 8985:80
  volumes:
    - .:/var/www/html/
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: smirnov/grpc:v1
  ports:
    - "9000:9000"
  volumes:
    - .:/var/www/html/